[build]
  command = "prisma generate && next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  PRISMA_CLI_QUERY_ENGINE_TYPE = "library"
